nome = input("digite seu nome:")
cpf = input("digite seu cpf:")
dt = input('digite sua data de nascimento:')
cpf = int(cpf)
print(type(cpf))
dt = int(dt)
print(type(dt))
print("seu nome é:", nome)
print("seu cpf é:", cpf)
print("sua data de nascimento é:", dt)
